/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Grafica;

import Capa_Lógica.C_Cine;
import Capa_Lógica.D_Cliente;
import Capa_Lógica.B_Película;
import Capa_Lógica.Tipo_Tarjeta;

public class jFrm_A_Menu_Inicial extends javax.swing.JFrame {

    C_Cine cine;
    B_Película pelicula;
    D_Cliente cliente;
    Tipo_Tarjeta tipo_tarjeta;

    

    public jFrm_A_Menu_Inicial(C_Cine cine, B_Película pelicula, D_Cliente cliente, Tipo_Tarjeta tipo_tarjeta) {
        this.cine = cine;
        this.pelicula = pelicula;
        this.cliente = cliente;
        this.tipo_tarjeta = tipo_tarjeta;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtn_Administrar_Cartelera = new javax.swing.JButton();
        jBtn_Reservacion_y_compra = new javax.swing.JButton();
        jBtn_Salir = new javax.swing.JButton();
        jLbl_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        jPanel1.setLayout(null);

        jBtn_Administrar_Cartelera.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtn_Administrar_Cartelera.setForeground(new java.awt.Color(0, 153, 102));
        jBtn_Administrar_Cartelera.setText("Administrar cartelera");
        jBtn_Administrar_Cartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Administrar_CarteleraActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_Administrar_Cartelera);
        jBtn_Administrar_Cartelera.setBounds(50, 50, 270, 40);

        jBtn_Reservacion_y_compra.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtn_Reservacion_y_compra.setForeground(new java.awt.Color(0, 153, 102));
        jBtn_Reservacion_y_compra.setText("Reservación y compra");
        jBtn_Reservacion_y_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Reservacion_y_compraActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_Reservacion_y_compra);
        jBtn_Reservacion_y_compra.setBounds(47, 120, 280, 40);

        jBtn_Salir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtn_Salir.setForeground(new java.awt.Color(255, 51, 51));
        jBtn_Salir.setText("Salir");
        jBtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_Salir);
        jBtn_Salir.setBounds(100, 180, 170, 40);

        jLbl_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capa_Grafica/popcorn.png"))); // NOI18N
        jPanel1.add(jLbl_Image);
        jLbl_Image.setBounds(0, 0, 360, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtn_SalirActionPerformed

    private void jBtn_Administrar_CarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Administrar_CarteleraActionPerformed

        jFrm_B_1_Administrar_Cartelera ventana = new jFrm_B_1_Administrar_Cartelera(this.cine, this.pelicula, this.cliente, this.tipo_tarjeta);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_jBtn_Administrar_CarteleraActionPerformed

    private void jBtn_Reservacion_y_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Reservacion_y_compraActionPerformed
        jFrm_D_1_submenu_reservacion_y_compra ventana = new jFrm_D_1_submenu_reservacion_y_compra(this.cine, this.pelicula, this.cliente, this.tipo_tarjeta);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_jBtn_Reservacion_y_compraActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Administrar_Cartelera;
    private javax.swing.JButton jBtn_Reservacion_y_compra;
    private javax.swing.JButton jBtn_Salir;
    private javax.swing.JLabel jLbl_Image;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
