/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Grafica;

import Capa_Lógica.C_Cine;
import Capa_Lógica.D_Cliente;
import Capa_Lógica.B_Película;
import Capa_Lógica.Tipo_Tarjeta;

public class jFrm_C_2_Mostrar_estado_de_las_salas extends javax.swing.JFrame {

    C_Cine cine;
    B_Película pelicula;
    D_Cliente cliente;
    Tipo_Tarjeta tipo_tarjeta;

    public jFrm_C_2_Mostrar_estado_de_las_salas(C_Cine cine, B_Película pelicula, D_Cliente cliente,Tipo_Tarjeta tipo_tarjeta
) {
        this.cine = cine;
        this.pelicula = pelicula;
        this.cliente = cliente;
        this.tipo_tarjeta = tipo_tarjeta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLbl_Número_sala = new javax.swing.JLabel();
        jBtn_Mostrar_estado_salas = new javax.swing.JButton();
        jCbo_Salas = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtA_Código_asiento = new javax.swing.JTextArea();
        jBtn_Regresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtA_mostrar_sala = new javax.swing.JTextArea();
        jLbl_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estado de las salas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setLayout(null);

        jLbl_Número_sala.setForeground(new java.awt.Color(204, 204, 0));
        jLbl_Número_sala.setText("Número de sala");
        jPanel2.add(jLbl_Número_sala);
        jLbl_Número_sala.setBounds(10, 40, 89, 16);

        jBtn_Mostrar_estado_salas.setForeground(new java.awt.Color(0, 153, 51));
        jBtn_Mostrar_estado_salas.setText("Mostrar estado");
        jBtn_Mostrar_estado_salas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Mostrar_estado_salasActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn_Mostrar_estado_salas);
        jBtn_Mostrar_estado_salas.setBounds(10, 90, 190, 32);

        jCbo_Salas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbo_SalasActionPerformed(evt);
            }
        });
        jPanel2.add(jCbo_Salas);
        jCbo_Salas.setBounds(120, 40, 150, 26);

        jTxtA_Código_asiento.setColumns(20);
        jTxtA_Código_asiento.setRows(5);
        jTxtA_Código_asiento.setText("Códigos de asiento:\n\nO - Ocupado\n\nD - Desocupado");
        jScrollPane2.setViewportView(jTxtA_Código_asiento);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(280, 60, 223, 83);

        jBtn_Regresar.setForeground(new java.awt.Color(255, 51, 51));
        jBtn_Regresar.setText("Regresar");
        jBtn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RegresarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn_Regresar);
        jBtn_Regresar.setBounds(493, 20, 120, 32);

        jTxtA_mostrar_sala.setColumns(20);
        jTxtA_mostrar_sala.setRows(5);
        jScrollPane1.setViewportView(jTxtA_mostrar_sala);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 610, 250);

        jLbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capa_Grafica/parque-jurasico.jpg"))); // NOI18N
        jPanel2.add(jLbl_image);
        jLbl_image.setBounds(0, -40, 640, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.jTxtA_Código_asiento.setEditable(false);
        this.jTxtA_mostrar_sala.setEditable(false);
        this.jCbo_Salas.addItem("1");
        this.jCbo_Salas.addItem("2");
        this.jCbo_Salas.addItem("3");
        this.jCbo_Salas.setSelectedIndex(-1);
        this.jBtn_Mostrar_estado_salas.setEnabled(false);


    }//GEN-LAST:event_formWindowOpened

    private void jCbo_SalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbo_SalasActionPerformed

        if (this.jCbo_Salas.getSelectedIndex() != -1) {
            this.jBtn_Mostrar_estado_salas.setEnabled(true);
        }
    }//GEN-LAST:event_jCbo_SalasActionPerformed

    private void jBtn_Mostrar_estado_salasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Mostrar_estado_salasActionPerformed
        switch (this.jCbo_Salas.getSelectedIndex()) {
            case 0:
                this.jTxtA_mostrar_sala.setText(this.cine.toString_sala_1());
                break;

            case 1:
                this.jTxtA_mostrar_sala.setText(this.cine.toString_sala_2());
                break;
            case 2:
                this.jTxtA_mostrar_sala.setText(this.cine.toString_sala_3());
                break;
        }
    }//GEN-LAST:event_jBtn_Mostrar_estado_salasActionPerformed

    private void jBtn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtn_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Mostrar_estado_salas;
    private javax.swing.JButton jBtn_Regresar;
    private javax.swing.JComboBox<String> jCbo_Salas;
    private javax.swing.JLabel jLbl_Número_sala;
    private javax.swing.JLabel jLbl_image;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTxtA_Código_asiento;
    private javax.swing.JTextArea jTxtA_mostrar_sala;
    // End of variables declaration//GEN-END:variables
}
