/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Grafica;

import javax.swing.JOptionPane;
import Capa_Lógica.C_Cine;
import Capa_Lógica.D_Cliente;
import Capa_Lógica.B_Película;
import Capa_Lógica.Tipo_Tarjeta;

public class jFrm_C_4_Reporte_cantidad_de_asientos_reservados_en_cada_sala extends javax.swing.JFrame {

    C_Cine cine;
    B_Película pelicula;
    D_Cliente cliente;
    Tipo_Tarjeta tipo_tarjeta;

    public jFrm_C_4_Reporte_cantidad_de_asientos_reservados_en_cada_sala(C_Cine cine, B_Película pelicula, D_Cliente cliente, Tipo_Tarjeta tipo_tarjeta
    ) {
        this.cine = cine;
        this.pelicula = pelicula;
        this.cliente = cliente;
        this.tipo_tarjeta = tipo_tarjeta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBtn_Regresar = new javax.swing.JButton();
        jBtn_Mostrar_Asientos_Reservados = new javax.swing.JButton();
        jCbo_Salas = new javax.swing.JComboBox<>();
        jLbl_Número_sala = new javax.swing.JLabel();
        jLbl_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte cantidad de asientos reservados en cada sala");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 400, 140);

        jBtn_Regresar.setForeground(new java.awt.Color(255, 51, 51));
        jBtn_Regresar.setText("Regresar");
        jBtn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_Regresar);
        jBtn_Regresar.setBounds(10, 300, 170, 32);

        jBtn_Mostrar_Asientos_Reservados.setForeground(new java.awt.Color(51, 255, 0));
        jBtn_Mostrar_Asientos_Reservados.setText("Mostrar cantidad asientos reservados");
        jBtn_Mostrar_Asientos_Reservados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Mostrar_Asientos_ReservadosActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_Mostrar_Asientos_Reservados);
        jBtn_Mostrar_Asientos_Reservados.setBounds(10, 100, 340, 32);

        jCbo_Salas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbo_SalasActionPerformed(evt);
            }
        });
        jPanel1.add(jCbo_Salas);
        jCbo_Salas.setBounds(180, 60, 33, 26);

        jLbl_Número_sala.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbl_Número_sala.setForeground(java.awt.Color.magenta);
        jLbl_Número_sala.setText("Número de sala");
        jPanel1.add(jLbl_Número_sala);
        jLbl_Número_sala.setBounds(10, 60, 130, 19);

        jLbl_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capa_Grafica/harry potter.jpg"))); // NOI18N
        jPanel1.add(jLbl_Image);
        jLbl_Image.setBounds(0, 0, 490, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.jCbo_Salas.addItem("1");
        this.jCbo_Salas.addItem("2");
        this.jCbo_Salas.addItem("3");
        this.jCbo_Salas.setSelectedIndex(-1);
        this.jTextArea1.setEditable(false);
    }//GEN-LAST:event_formWindowOpened

    private void jBtn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtn_RegresarActionPerformed

    private void jCbo_SalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbo_SalasActionPerformed

    }//GEN-LAST:event_jCbo_SalasActionPerformed

    private void jBtn_Mostrar_Asientos_ReservadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Mostrar_Asientos_ReservadosActionPerformed
        if (this.jCbo_Salas.getSelectedIndex() != -1) {

            switch (this.jCbo_Salas.getSelectedIndex()) {
                case 0:
                    this.jTextArea1.setText("La cantidad de asientos"
                            + "reservados en sala 1 es:"
                            + this.cine.getCant_asientos_sala_1());
                    break;
                case 1:
                    this.jTextArea1.setText("La cantidad de asientos"
                            + "reservados en sala 2 es:"
                            + this.cine.getCant_asientos_sala_2());
                    break;
                case 2:
                    this.jTextArea1.setText("La cantidad de asientos"
                            + "reservados en sala 3 es:"
                            + this.cine.getCant_asientos_sala_3());
                    break;

            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una sala", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtn_Mostrar_Asientos_ReservadosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Mostrar_Asientos_Reservados;
    private javax.swing.JButton jBtn_Regresar;
    private javax.swing.JComboBox<String> jCbo_Salas;
    private javax.swing.JLabel jLbl_Image;
    private javax.swing.JLabel jLbl_Número_sala;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
